awsRegion: ${aws_region}

autoDiscovery:
  clusterName: ${eks_cluster_id}
extraArgs:
  aws-use-static-instance-list: true

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
